import type { Config } from "tailwindcss";
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bayaro: {
          navy: "#0A1F54",
          blue: "#135FEF",
          aqua: "#22D3EE",
          slate: "#1E293B",
          soft: "#F5F8FF",
        },
        "secondary-fixed": "#dae3f7",
        "on-primary-fixed": "#00174b",
        "outline": "#737686",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#131c2a",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "secondary": "#565f6f",
        "primary-container": "#2563eb",
        "on-secondary-container": "#5c6575",
        "secondary-fixed-dim": "#bec7da",
        "on-tertiary-container": "#bdffdb",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "inverse-primary": "#b4c5ff",
        "background": "#f8f9ff",
        "surface-container": "#e5eeff",
        "inverse-surface": "#213145",
        "on-background": "#0b1c30",
        "on-surface-variant": "#434655",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-container": "#eeefff",
        "surface-tint": "#0053db",
        "secondary-container": "#dae3f7",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "on-secondary-fixed-variant": "#3e4757",
        "tertiary-fixed-dim": "#4edea3",
        "tertiary-container": "#007d55",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-high": "#dce9ff",
        "primary-fixed": "#dbe1ff",
        "primary": "#004ac6",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-fixed": "#002113",
        "outline-variant": "#c3c6d7",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#006242"
      },
      borderRadius: {
        "4xl": "2rem",
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "section-margin": "40px",
        "card-gap": "24px",
        "container-padding": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max-width": "1200px",
        "sidebar-width": "320px",
        "unit": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }]
      },
      boxShadow: {
        soft: "0 18px 50px rgba(10, 31, 84, 0.08)",
      },
      keyframes: {
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-8px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(8px)" },
        },
      },
      animation: {
        shake: "shake 0.6s ease-in-out",
      },
    },
  },
  plugins: [
    containerQueries,
    forms,
  ],
};

export default config;
